image: Visual Studio 2017
version: '{branch}-{build}'
configuration:
- Release
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- nuget install Cake -ExcludeVersion
build_script:
- .\Cake\Cake.exe --target=Build --buildNumber=%APPVEYOR_BUILD_NUMBER% --currentBranch=%APPVEYOR_REPO_BRANCH%
test_script:
- .\Cake\Cake.exe --target=UnitTest
after_test:
- .\Cake\Cake.exe --target=Pack --buildNumber=%APPVEYOR_BUILD_NUMBER% --currentBranch=%APPVEYOR_REPO_BRANCH%
- .\Cake\Cake.exe --target=Push --mygetApiKey=%MYGET_API_KEY%
artifacts:
- path: out\*
